export const ALL_CURRENCIES_TRIGGERED = "ALL_CURRENCIES_TRIGGERED";
export const ALL_CURRENCIES_REQUEST = "ALL_CURRENCIES_REQUEST";
export const ALL_CURRENCIES_SUCCESS = "ALL_CURRENCIES_SUCCESS";
export const ALL_CURRENCIES_FAILURE = "ALL_CURRENCIES_FAILURE";
